Added some exiftool scripts.

diff --git a/Change JPEG date b/Change JPEG date
--- a/Change JPEG date
+++ b/Change JPEG date
@@ -1,18 +1,22 @@
 #!/bin/bash
-MONODIS=/tank/opt/mono/bin/monodis
 
 function process {
 	local filename="$1"
+	local newDate="$2"
+	exiftool -ModifyDate="$newDate" "$filename"
 
-	# separate initialization because local sets the $? to zero
-	local version=""
-	version=$($MONODIS --assembly "$filename" | grep Version)
-	if [ $? -eq 0 ]; then
-		zenity --info --text="Version of $filename: $version"
-	else
-		zenity --error --text="Could not determine version of $filename"
+	if [ $? -ne 0 ]; then
+		zenity --error --text="Could not process $filename"
 	fi
 }
+
+newDate=$(zenity --entry --title="Change date" \
+	--text="Enter date time for the JPEG images" \
+	--entry-text="YYYY-MM-dd HH:mm:ss")
+
+if [ $? -ne 0 ]; then
+	exit 1
+fi
 
 while read filename; do
 	if [ -n "$filename" ]; then
@@ -21,8 +25,7 @@ while read filename; do
 		elif [ ! -s "$filename" ]; then
 			zenity --error --text "File $filename is empty."
 		else
-			process "$filename"
+			process "$filename" "$newDate"
 		fi
 	fi
 done < <(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")
-
diff --git a/Rename JPEG file based on ModifyDate b/Rename JPEG file based on ModifyDate
--- a/Rename JPEG file based on ModifyDate
+++ b/Rename JPEG file based on ModifyDate
@@ -1,16 +1,11 @@
 #!/bin/bash
-MONODIS=/tank/opt/mono/bin/monodis
 
 function process {
 	local filename="$1"
+	exiftool "-FileName<ModifyDate" -d "%Y-%m-%d %H%M%S.%%e" "$filename"
 
-	# separate initialization because local sets the $? to zero
-	local version=""
-	version=$($MONODIS --assembly "$filename" | grep Version)
-	if [ $? -eq 0 ]; then
-		zenity --info --text="Version of $filename: $version"
-	else
-		zenity --error --text="Could not determine version of $filename"
+	if [ $? -ne 0 ]; then
+		zenity --error --text="Could not process $filename"
 	fi
 }
 
@@ -25,4 +20,3 @@ while read filename; do
 		fi
 	fi
 done < <(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")
-
